name: 📚 Documentation Issue
description: Report outdated, missing, or unclear documentation
title: "[Docs]: "
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide as much detail as possible.

  - type: input
    id: page
    attributes:
      label: Documentation Page/URL
      description: Provide a link or filename for the affected documentation (e.g., CONTRIBUTING.md, README.md, source file).
      placeholder: e.g., README.md
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's the issue?
      description: What’s missing, incorrect, or confusing about the documentation?
      placeholder: Clearly describe the documentation problem
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested fix or clarification (optional)
      description: If you have a suggested improvement or wording change, include it here.
      placeholder: "I think it would help if..."
