name: "\u2728 Feature Request"
description: Suggest a new idea, feature, or enhancement.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in improving EntityAxis. Please provide as much detail as possible to help us evaluate your suggestion.

  - type: input
    id: package
    attributes:
      label: Related Package (if applicable)
      placeholder: e.g. EntityAxis.MediatR

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added or changed?
      placeholder: Describe the feature here
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: What problem does this solve, or what value does it add?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I have read and agree to follow this project's [Code of Conduct](../CODE_OF_CONDUCT.md)
          required: true
