name: Main Status

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore ./src/EntityAxis.sln

    - name: Build
      run: dotnet build ./src/EntityAxis.sln --no-restore /m

    - name: Test
      run: >-
        dotnet test ./src/EntityAxis.sln
        --no-build
        --verbosity normal
        --logger trx
        --collect:"XPlat Code Coverage"
        -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      env:
        GitHubAccessToken: ${{ secrets.GITHUBACCESSTOKEN }}

    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@fcebab03f26c7530a22baa63f06b3e0515f0c7cd
      # https://github.com/codecov/codecov-action
      uses: codecov/codecov-action@v5
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: ${{ secrets.CODECOV_TOKEN }}
        # Directory to search for coverage reports.
        directory: ./