# .github/workflows/semantic-pr.yml
name: Conventional PR Title Check
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: feat, fix, chore, refactor, test, docs, style, perf, ci, build, revert
          requireScope: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
